egra/account/urls.py
from django.urls import path

from . import views

app_name = 'account'
urlpatterns = [
    path('register/', views.register, name="register"),
]

egra/egra/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('graphs.urls')),
    path('account/', include('account.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) 

egra/graphs/urls.py
from django.urls import path

from . import views

app_name = 'graphs'
urlpatterns = [
	path('', views.projects, name="projects"),
    path('projects_of/<int:user_id>', views.projects_of, name="projects_of"),
    path('public_projects/', views.public_projects, name="public_projects"),
    path('create_project/', views.create_project, name="create_project"),
    path('project/<int:project_id>', views.project, name="project"),
    path('save_project/<int:project_id>', views.save_project, name="save_project"),
    path('edit_project/<int:project_id>', views.edit_project, name="edit_project"),
    path('delete_project/<int:project_id>', views.delete_project, name="delete_project"),
]

egra/account/models.py
from django.db import models

# Create your models here.

egra/graphs/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_delete
from django.dispatch import receiver

class Project(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1, related_name='+')
    name = models.CharField("Name of project", max_length = 30)
    data = models.TextField("Data of project", default = "")
    preview = models.ImageField("Preview of project", upload_to="previews/", default="/previews/default-preview.jpg")
    creation_date = models.DateField("Creation date", default = timezone.now())

    def __str__(self):
        return str(self.name)

    def delete(self, *args, **kwargs):
        self.preview.delete()
        super(Project, self).delete(*args, **kwargs)


@receiver(post_delete, sender=Project)
def delete_project_images(sender, instance, **kwargs):
    instance.preview.delete(save=False)

egra/account/forms.py
from django.contrib.auth.models import User
from django import forms

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

egra/account/views.py
from django.shortcuts import render, reverse
from .forms import UserRegistrationForm
from django.contrib.auth import authenticate, login
from django.http import Http404, HttpResponseRedirect, JsonResponse
from django.contrib import messages

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()

            login(request, new_user)

            return HttpResponseRedirect(reverse('graphs:projects'))
    else:
        user_form = UserRegistrationForm()
    return render(request, 'account/register.html', {'user_form': user_form})

egra/graphs/views.py
from django.shortcuts import render, reverse
from django.http import Http404, HttpResponseRedirect, JsonResponse
from django.utils import timezone
from .models import *
from django.core.files.base import ContentFile
import base64


def projects(request):
    if request.user.is_authenticated:
        projects = Project.objects.filter(user = request.user).order_by("-creation_date")
    
    else:
        projects = None

    return render(request, 'graphs/projects.html', {'projects': projects})

def public_projects(request):
    all_projects = Project.objects.order_by('-creation_date')
    if request.user.is_authenticated:
        projects = all_projects.exclude(user=request.user)
    else:
        projects = all_projects

    return render(request, 'graphs/public_projects.html', {'projects': projects})

def projects_of(request, user_id):

    requested_user = User.objects.get(id = user_id)

    projects = Project.objects.order_by('-creation_date').filter(user = requested_user)

    return render(request, 'graphs/public_projects.html', {'projects': projects, "requested_user": requested_user})


def project(request, project_id):
    project = Project.objects.get(id = project_id)

    return render(request, 'graphs/project.html', {'project': project})


def create_project(request):
    project = Project.objects.create(
        user = request.user,
        name = "New project",
        preview = 'media/default-preview.jpg',
        creation_date = timezone.now(),
    )

    return HttpResponseRedirect(reverse('graphs:project', args=(project.id, )))

def save_project(request, project_id):
    project = Project.objects.get(id = project_id)

    project.data = request.POST['saved_data']
    data_url = request.POST['new_preview']
    image_data = data_url.split(',')[1]
    decoded_image_data = base64.b64decode(image_data)

    project.preview.save(f'preview.jpg', ContentFile(decoded_image_data), save=True)

    project.save()

    return HttpResponseRedirect(reverse('graphs:project', args=(project.id, )))

def edit_project(request, project_id):
    project = Project.objects.get(id = project_id)

    project.name = request.POST['project_name']
    project.save()

    return HttpResponseRedirect(reverse('graphs:project', args=(project.id, )))

def delete_project(request, project_id):
    project = Project.objects.get(id = project_id)

    project.delete()

    return HttpResponseRedirect(reverse('graphs:projects'))

egra/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}EGRA{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/graphs.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <script src="{% static 'libs/wow.min.js' %}"></script>

    <script src="{% static 'libs/p5.js' %}"></script>
    <script src="{% static 'libs/jQuery.min.js' %}"></script>
    <script src="{% static 'libs/jquery-ui.min.js' %}"></script>
</head>
<body>
    
    <div class="menu">
        <div class="logo">
            <h1 style="color: white;">EGRA</h1>
        </div>
        <div class="inner-menu">
            <a href="#" class="menu-link">About</a>
            <a href="{% url 'graphs:public_projects' %}" class="menu-link">Public Projects</a>
            {% if user.is_authenticated %}
                <a href="{% url 'graphs:projects' %}" class="menu-link">Your Projects</a>
                <a class="menu-link" href="{% url 'logout'%}?next={% url 'graphs:projects' %}">Logout</a>
            {% else %}
                <a class="menu-link" href="{% url 'login'%}?next={{request.path}}">Login</a>
            {% endif %}
        </div>

    </div>

    {% block content %}{% endblock %}
</body>
</html>

egra/templates/graphs/project.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{project.name}}{% endblock %}

{% block content %}

    {% if request.user != project.user %}
        <style>
            .saving {
                display: none;
            }
            .remove-graph-button {
                display: none;
            }
        </style>
        <script>
            $(document).ready(function() {
                $(".settings-input").attr("readonly", "true");
                $(".header-input").attr("readonly", "true");
                $(".settings-input-small").attr("readonly", "true");
                $(".settings-select").attr("disabled", "true");
            });
        </script>
    {% endif %}
    <div class="sidebar">
        <div class="sidebar-block project-settings">
            {% if request.user == project.user %}
            <form method = "POST" action="{% url 'graphs:edit_project' project.id %}">
                {% csrf_token %}
                <input type="text" name="project_name" id="saving-project_name" class="standart-input" value="{{project.name}}">
                <button class="popFunc" style="width:100%;" type="sumbit">Apply changes</button>
            </form>
            {% else %}
                <p>Project name: {{project.name}}</p>
            {% endif %}
        </div>
        {% if request.user == project.user %}
        <div class="sidebar-block mostPopularFunctions">
            <a class="popFunc" href="#" id="custom">Add Custom Graph</a>
            <br>
            <hr>
            <br>
            <a class="popFunc" href="#" id="parabola">Add Parabola Graph</a>
            <a class="popFunc" href="#" id="yx">Add y = x Graph</a>
            <a class="popFunc" href="#" id="sinGraph">Add Sin Graph</a>
            <a class="popFunc" href="#" id="cosGraph">Add Cos Graph</a>
            <a class="popFunc" href="#" id="hyperbolaGraph">Add Hyperbola Graph</a>
        </div>
        {% endif %}
        <div class="sidebar-block graphs">
            <p id="your-graphs-here">Your graphs here</p>
        </div>  
        <div class="sidebar-block dotInformation">
            <p style="font-weight: bold;" id="dot-information-here">Dot information here</p>
        </div>
        
        <div class="sidebar-block saving">
            <form method = "POST" action="{% url 'graphs:save_project' project.id %}">
                {% csrf_token %}
                <input type="text" name="saved_data" id="saving-area" style="display:none;" value="{{project.data}}">
                
                <input type="text" name="new_preview" id="preview" style="display:none;" value="{{project.preview.url}}">
                {% if request.user == project.user %}
                <button class="popFunc save" type="sumbit">Save project</button>
                {% endif %}
            </form>
        </div>
        {% if request.user == project.user %}
        <div class="sidebar-block deleting_project">
            <a class="popFunc delete_project-in" style="width: auto; background: red; font-weight: bold;" href="#">Delete Project</a>
            <div class="are_you_sure" style="display: none;">
                <p>Are you sure that you want to delete your project?</p>
                <a class="popFunc delete_project-back" style="width: auto; background: green; font-weight: bold;" href="#">NO, I AM NOT</a>
                <br>
                <hr>
                <br>
                <a class="small-button" href="{% url 'graphs:delete_project' project.id %}">Yes, I am sure</a>
            </div>
        </div>
        {% endif %}
    </div>
    

    <div class="modal-windows">
 
    </div>

    <script src="{% static 'js/elements/dot.js' %}"></script>
    <script src="{% static 'js/elements/graph.js' %}"></script>

    <script src="{% static 'js/interface_handler.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
{% endblock %}

egra/templates/graphs/projects.html
{% extends 'base.html' %}
{% load static %}
{% block title %}EGRA - Projects{% endblock %}

{% block content %}


        <div class="block please-login-to-create-projects">
            <div class="block-background">
                <canvas id="please-login-to-create-projects"></canvas>
            </div>	
            <div class="block-content">
                
                    {% if user.is_authenticated %}
                        <br>
                        <br>
                        <h1>Your projects: </h1>
                        <br>
                        <hr>
                        <br>
                        <div class="projects">
                            {% if projects %}

                                {% for project in projects %}
                                    <div class="project">
                                        <div class="preview" style="background-image: url('{{ project.preview.url }}')">
        
                                        </div>
                                        <br>
                                        <hr>
                                        <div class="info">
                                            <a href="{% url 'graphs:project' project.id %}">{{project.name|truncatechars_html:40}}</a>
                                            <em>{{project.creation_date}}</em>
                                        </div>
                                    </div>                                
                                {% endfor %}

                            {% else %}
                                    <p>You haven't created any projects yet.</p>
                            {% endif %}


                        </div>
                        <br>
                        <br>
                        <a style="display: block; width: 300px; text-align:center;" class="main-button" href="{% url 'graphs:create_project' %}" class="new-project">Create new project</a>


                    {% else %}
                    <center class="inner-content">
                        <p style="font-size: 35px;" class="wow animate__animated animate__fadeInUp">You have to <b>login</b> to create projects</p>  
                        <br>
                        <hr>
                        <br>
                        <p style="font-size:30px;" class="wow animate__animated animate__fadeInUp" data-wow-delay=".5s">
                            <a class="main-button wow animate__animated animate__fadeInUp" href="{% url 'login'%}?next={{request.path}}" data-wow-delay=".3s">Log in</a>
                            or
                            <a class="main-button wow animate__animated animate__fadeInUp" href="{% url 'account:register'%}" data-wow-delay=".9s">Sign up</a>
                        </p>
                    </center> 
                    {% endif %}
                            
            </div>		
        </div>
        <script src="{% static 'js/ui/please-login-to-create-projects.js' %}"></script>

{% endblock %}

egra/templates/graphs/public_projects.html
{% extends 'base.html' %}
{% load static %}
{% block title %}EGRA - Projects{% endblock %}

{% block content %}


        <div class="block please-login-to-create-projects">
            <div class="block-background">
                <canvas id="please-login-to-create-projects"></canvas>
            </div>	
            <div class="block-content">
                
                        <br>
                        <br>
                        {% if requested_user %}
                            <h1>{{requested_user.get_username}}`s projects: </h1>
                        {% else %}
                            <h1>Projects of our community: </h1>
                        {% endif %}
                        <br>
                        <hr>
                        <br>
                        <div class="projects">
                            {% if projects %}
                                {% for project in projects %}
                                    <div class="project">
                                        <div class="preview" style="background-image: url('{{ project.preview.url }}')">
        
                                        </div>
                                        <br>
                                        <hr>
                                        <div class="info">
                                            <a href="{% url 'graphs:project' project.id %}">{{project.name|truncatechars_html:40}}</a>
                                            <em>{{project.creation_date}}</em>
                                            {% if not requested_user %}
                                            <a href="{% url 'graphs:projects_of' project.user.id %}">{{project.user.get_username}}</a>
                                            {% endif %}
                                        </div>
                                    </div>                                
                                {% endfor %}

                            {% else %}
                                    <p>Users haven't created any projects yet.</p>
                            {% endif %}


                        </div>
                            
            </div>		
        </div>
        <script src="{% static 'js/ui/please-login-to-create-projects.js' %}"></script>

{% endblock %}